{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{foreach $tsinfo.channellist as $tsinfochannel}
    {if $tsinfochannel.parent|eq($startnode)}
        <tr class="tsline">
            <td>
                {for 0 to $depth as $value}
                    {set $recurse_buffer='teamspeakdisplay/treeimage1.png'}
                    {if $value|eq(0)}{continue}{/if}
                    {if $value|eq($depth)}{set $recurse_buffer='teamspeakdisplay/treeimage2.png'}{/if}
                    <img src="{$recurse_buffer|ezimage('no')}" alt="Channel" />
                {/for}
                <img src="{'teamspeakdisplay/channel.png'|ezimage('no')}" alt="Channel" />
                <span class="tsdisplaytext">
                    {set $recurse_buffer = TeamspeakUTF8Output( $tsinfochannel.displayname )}
                    {$recurse_buffer|wash()}
                    {if $tsinfochannel.topic|count()|gt(0)}
                        {set $recurse_buffer = TeamspeakUTF8Output( $tsinfochannel.topic )}
                        <span style="font-size:0.8em;"> ({$recurse_buffer|wash()})</span>
                    {/if}
                </span>
            </td>
        </tr>
        {foreach $tsinfo.playerlist as $tsinfoplayer}
            {if $tsinfoplayer.channelid|eq($tsinfochannel.channelid)}
                <tr class="tsline">
                    <td>
                        {for 0 to $depth|inc() as $value}
                            {set $recurse_buffer='teamspeakdisplay/treeimage1.png'}
                            {if $value|eq(0)}{continue}{/if}
                            {if $value|eq($depth|inc())}{set $recurse_buffer='teamspeakdisplay/treeimage2.png'}{/if}
                            <img src="{$recurse_buffer|ezimage('no')}" alt="" />
                        {/for}
                        {set $recurse_buffer = concat('teamspeakdisplay/player_',$tsinfoplayer.displayimage,'.png')}
                        <img src="{$recurse_buffer|ezimage('no')}" alt="Player" />
                        <span class="tsdisplaytext">
                            {set $recurse_buffer = TeamspeakUTF8Output( $tsinfoplayer.displayname )}
                            {$recurse_buffer|wash()}
                        </span>
                    </td>
                </tr>
            {/if}
        {/foreach}
        {include uri="design:teamspeakdisplay/recursive_channel.tpl" tsinfo=$tsinfo startnode=$tsinfochannel.channelid depth=$depth|sum(1)}
    {/if}
{/foreach}
