{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{set-block scope=global variable=cache_ttl}0{/set-block}

{def $tsbuffer=''}

<h1>{$node.name|wash()}</h1>

{def $settings = hash( 'serveraddress',          $node.data_map.serveraddress.value,
                       'serverudpport',      int($node.data_map.serverudpport.value),
                       'serverqueryport',    int($node.data_map.serverqueryport.value),
                       'limitchannel',           $node.data_map.limitchannel.value,
                       'forbiddennicknamechars', $node.data_map.forbiddennickchars.value
)}
{def $tsinfo = displayTeamspeakEx( $settings )}

{if $tsinfo.queryerror|eq(0)}
    <div id="teamspeakdisplay">
        <table>
            <tr><td>
                <img src="{'teamspeakdisplay/info.png'|ezimage('no')}" alt="" />
                <span class="tsdisplaytext">
                    {'Server Name'|i18n('extension/teamspeakdisplay')}:
                    {*$tsinfo.serverinfo.server_name*}
                    {set $tsbuffer = TeamspeakUTF8Output( $tsinfo.serverinfo.server_name )}
                    {$tsbuffer|wash()}
                    {if $tsinfo.serverinfo.server_password|eq('1')}
                        <span style="font-size:0.8em;"> ({'password protected'|i18n('extension/teamspeakdisplay')}</span>)
                    {/if}
                </span>
            </td></tr>
            <tr><td>
                <img src="{'teamspeakdisplay/info.png'|ezimage('no')}" alt="" />
                <span class="tsdisplaytext">
                    {'Message'|i18n('extension/teamspeakdisplay')}:
                    {*$tsinfo.serverinfo.server_welcomemessage*}
                    {set $tsbuffer = TeamspeakUTF8Output( $tsinfo.serverinfo.server_welcomemessage )}
                    {$tsbuffer|wash()}
                </span>
            </td></tr>
            <tr><td>
                <img src="{'teamspeakdisplay/info.png'|ezimage('no')}" alt="" />
                <span class="tsdisplaytext">
                    {'Address'|i18n('extension/teamspeakdisplay')}:
                    <a href="teamspeak://{$node.data_map.serveraddress.value}:{$tsinfo.serverinfo.server_udpport}">{$node.data_map.serveraddress.value}:{$tsinfo.serverinfo.server_udpport}</a>
                </span>
            </td></tr>
            <tr><td>
                <img src="{'teamspeakdisplay/info.png'|ezimage('no')}" alt="" />
                <span class="tsdisplaytext">{'Users'|i18n('extension/teamspeakdisplay')}: {$tsinfo.serverinfo.server_currentusers}/{$tsinfo.serverinfo.server_maxusers}
                in {$tsinfo.serverinfo.server_currentchannels} {'Channels'|i18n('extension/teamspeakdisplay')}</span>
            </td></tr>
        </table>
        <br />
        <table>
            {def $recurse_buffer=0}
            {def $recurse_array=array()}
            {def $recurse_users=array()}
            {include uri="design:teamspeakdisplay/recursive_channel.tpl" tsinfo=$tsinfo startnode=-1 depth=0}
        </table>
    </div>
{else}
    {'TS Server currently offline or could not connect.'|i18n('extension/teamspeakdisplay')}
{/if}

{undef $tsbuffer}
